### ISSUE TITLE
Tempo_lightgbm.ipynb and GUI.exe 

### ISSUE THREAD

**Issue by nikolayrantsev** [Aturt2/music-sheet-generator#2]
Hi, 

This question might sound simple, but for me as a beginner, it's the big question) 
Could you please provide with more details on this point, according to the instruction: ->

> How do I install the project?
> Installation is quite tricky at the moment. To be safe you should (with conda at least):
> 
> Clone this repository.
> Install pip version 18.1 conda install pip==18.1
> Create a new environment from the exported one provided conda env create -f environment.yml -n your_env_name
> Install requirements pip install -r requirements.txt
> NOTE: You should re-train the LightGBM model by running the "Tempo/Tempo_lightgbm.ipynb" notebook if you want to use the pipeline in any way.

I'm browsing the source code looking for  `Tempo_lightgbm.ipynb` file and can't find it. Is this something created after the prev steps?

Then, 
> 
> How do I use the application?
> Run "GUI.exe" located in "Final_app/dist/GUI".

`GUI.exe`  should be here? 
https://github.com/Aturt2/music-sheet-generator/tree/master/GUI
Or it's generated during the correct installation flow?

Thank you for any inputs on that!

**Comment by aomartinezg** [comment]
Unfortunately, due to GitHub's size limitations I had to remove some of the larger files. That's why some files might be missing.

Are you trying to run the final app?

**Comment by nikolayrantsev** [comment]
This question might bring some light -
Can you please elaborate - how does Final app appear?  Is this the same as the source code in GitHub or not?

**Comment by aomartinezg** [comment]
With the current code in this repo the folder "Final_app" will not appear. I had to remove it due to space limitations. However, if you are interested in trying it, I might be able to make a simplified notebook version that could be smaller.

**Comment by nikolayrantsev** [comment]
Yes, please, it'll be very helpful,
thank you

**Comment by aomartinezg** [comment]
Done! In the "GUI" directory you can find "GUI.ipynb", which is a python notebook that emulates the app. It runs an older version but it has the same features as the latest. I have also included some guitar recordings in "Demo_recordings", which you can use to test the app if you don't have recordings of your own.

**Comment by nikolayrantsev** [comment]
Thank you so much
